#!/usr/bin/env ruby
require_relative "./command_helper"

first_option = ARGV[0]
rest_options = (ARGV[1..-1] || []).join(" ")

case first_option
when "ruby_2_5", "ruby 2.5", "2.5"
  system! "touch Gemfile.lock.ruby_2_5"
  system! "docker compose build ruby_2_5"
  system! %Q{docker compose run --rm ruby_2_5   bash -c "bundle check || bundle install"}
when "ruby_2_6", "ruby 2.6", "2.6"
  system! "touch Gemfile.lock.ruby_2_6"
  system! "docker compose build ruby_2_6"
  system! %Q{docker compose run --rm ruby_2_6   bash -c "bundle check || bundle install"}
when "ruby_2_7", "ruby 2.7", "2.7"
  system! "touch Gemfile.lock.ruby_2_7"
  system! "docker compose build ruby_2_7"
  system! %Q{docker compose run --rm ruby_2_7   bash -c "bundle check || bundle install"}
when "ruby_3_0", "ruby 3.0", "3.0"
  system! "touch Gemfile.lock.ruby_3_0"
  system! "docker compose build ruby_3_0"
  system! %Q{docker compose run --rm ruby_3_0   bash -c "bundle check || bundle install"}
when "ruby_3_1", "ruby 3.1", "3.1"
  system! "touch Gemfile.lock.ruby_3_1"
  system! "docker compose build ruby_3_1"
  system! %Q{docker compose run --rm ruby_3_1   bash -c "bundle check || bundle install"}
when "jruby_9_2", "jruby", "jruby 9.2", "9.2"
  system! "touch Gemfile.lock.jruby"
  system! "docker compose build jruby_9_2"
  system! %Q{docker compose run --rm jruby_9_2  bash -c "bundle check || bundle install"}
when "all"
  system! "touch Gemfile.lock.ruby_2_5"
  system! "touch Gemfile.lock.ruby_2_6"
  system! "touch Gemfile.lock.ruby_2_7"
  system! "touch Gemfile.lock.ruby_3_0"
  system! "touch Gemfile.lock.ruby_3_1"
  system! "touch Gemfile.lock.jruby"

  system! "docker compose build"

  system! %Q{docker compose run --rm ruby_2_5   bash -c "bundle check || bundle install"}
  system! %Q{docker compose run --rm ruby_2_6   bash -c "bundle check || bundle install"}
  system! %Q{docker compose run --rm ruby_2_7   bash -c "bundle check || bundle install"}
  system! %Q{docker compose run --rm ruby_3_0   bash -c "bundle check || bundle install"}
  system! %Q{docker compose run --rm ruby_3_1   bash -c "bundle check || bundle install"}
  system! %Q{docker compose run --rm jruby_9_2  bash -c "bundle check || bundle install"}
else
  system! "touch Gemfile.lock.ruby_3_1"
  system! "docker compose build ruby_3_1"
  system! %Q{docker compose run --rm ruby_3_1   bash -c "bundle check || bundle install"}
end
