name: Ruby

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        active_model:
          - '6.0'
          - '6.1'
          - '7.0'
          - '7.1'
        http_client_gem:
          - 'rest-client'
          - 'faraday'

    env:
      ACTIVE_MODEL_VERSION: "~> ${{ matrix.active_model }}.0"
      HTTP_CLIENT_GEM: "${{ matrix.http_client_gem }}"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
